### PR TITLE
Initial version of kaldi rescorer.

### PR DESCRIPTION
**Pull request by psmit**

### CODE REVIEW

**Comment by psmit** [comment]
In principle this can be merged, but it would need some checking from you.

- In a couple place there are now logging statements instead of print statements. This might not work always
- At this moment there is a heuristic for tightening the pruning parameters if the lattice is large. Probably that should be made configurable
- There might be too much logging in some places

You can merge now, or wait until I'm back from holiday (3 weeks), after which I should have some time to clean it up a bit.

**Comment by senarvi** [comment]
We can wait 3 weeks. Maybe you could also add short instructions how to use this with Kaldi lattices in this file: https://github.com/senarvi/theanolm/blob/master/docs/applying.rst

The reason that you changed the print statements, was it because you want to output the lattice to standard output? The only problem I see is that the user might not always see error messages. Maybe user messages should be written to standard error?

Anyway, let's continue from this after your vacation.

**Comment by psmit** [comment]
I have now moved all heuristics to command line options and wrote some documentation. Only some testing is now left.

**Comment by senarvi** [comment]
Thank's a lot Peter for this!

**Pull request merged**
